name: Deploy NestJS to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Login to Railway
        run: |
          echo "${{ secrets.RAILWAY_API_KEY }}" | railway login --api-key

      - name: Deploy to Railway
        run: |
          railway up --project=<your_project_id> --env=<your_environment>
